name: Synapse Monitor

on:
  workflow_dispatch:

  schedule:
    - cron: '0 14 * * 1-5'
      timezone: "Asia/Kolkata"

    - cron: '10 18 * * 1-5'
      timezone: "Asia/Kolkata"

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Synapse monitor
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          SYNAPSE_ENDPOINT: ${{ secrets.SYNAPSE_ENDPOINT }}
        run: |
          python synapse_monitor.py
